#!/sbin/openrc-run

name="$SVCNAME"
supervisor="supervise-daemon"
command="/usr/bin/$SVCNAME"
command_user="acmednsproxy"
command_args="serve ${ACMEDNSPROXY_OPTS}"
extra_started_commands="reload log"
supervise_daemon_args="--stdout '${ACMEDNSPROXY_LOG_FILE}' --stderr '${ACMEDNSPROXY_LOG_FILE}'"

depend() {
        need net localmount
        use logger
        after firewall
}

reload() {
        ${supervisor} ${RC_SVCNAME} --signal HUP
}

log() {
        cat "${ACMEDNSPROXY_LOG_FILE}"
}
