on:
  push:
    branches:
    - main

name: Make Relase
jobs:
  glibc:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - run: go version
      - name: Build htcrypt
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ./build/ ./cmd/htcrypt
      - name: Build acmednsproxy
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ./build/ ./cmd/acmednsproxy
      - uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-${{ matrix.goos }}-${{ matrix.goarch }}-libc
          path: ./build/*
          if-no-files-found: error
  musl:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    
    steps:
      - uses: actions/checkout@v3
      - uses: docker://golang:alpine
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        with:
          args: go build -o ./build/ ./cmd/htcrypt
      - uses: docker://golang:alpine
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        with:
          args: go build -o ./build/ ./cmd/acmednsproxy
      - uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-${{ matrix.goos }}-${{ matrix.goarch }}-musl
          path: ./build/*
          if-no-files-found: error
  flaf:
    needs: [glibc, musl]
    name: Flaf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-linux-amd64
          path: artifact/linux-amd64
      - name: Display structure of downloaded files
        run: ls -R