on:
  push:
    branches:
    - main

name: Make Snapshot
jobs:
  gorelease:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update -y -q
          sudo apt-get install -y -q musl-dev
          pip install jinja2-cli[yaml]
          make
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config goreleaser.yaml --rm-dist --snapshot
      - name: Move apks
        run: |
          set -ex
          mkdir apks
          cp dist/*.apk apks/
      - name: Push to apk repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.APK_SSH_KEY }}
        with:
          source-directory: 'apks'
          destination-github-username: 'KalleDK'
          destination-repository-name: 'apk'
          user-email: apk@k-moeller.dk
          target-branch: main
          target-directory: x86_64/acmednsproxy
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-archive
          path: |
            ./dist/*.zip
            ./dist/*.tar.gz
            ./dist/*.apk
            ./dist/*.deb
          if-no-files-found: error