on:
  push:
    branches:
    - main

name: Make Snapshot
jobs:
  gorelease:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Install Tools
        run: |
          set -ex
          sudo apt-get update -y -q
          sudo apt-get install -y -q musl-dev
          pip install jinja2-cli[yaml]
          make small
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config goreleaser-small.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'acmednsproxy-archive'
          path: |
            ./dist/*.zip
            ./dist/*.tar.gz
            ./dist/*.apk
            ./dist/*.deb
          if-no-files-found: error