on:
  push:
    branches:
    - main

name: Make Relase
jobs:
  archive:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_archive.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-archive
          path: |
            ./dist/acmednsproxy-archive/*.zip
            ./dist/acmednsproxy-archive/*.tar.gz
          if-no-files-found: error
  server:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_server.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-server
          path: |
            ./dist/acmednsproxy-server/*.deb
            ./dist/acmednsproxy-server/*.apk
          if-no-files-found: error
  tools:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_tools.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-tools
          path: |
            ./dist/acmednsproxy-tools/*.deb
            ./dist/acmednsproxy-tools/*.apk
          if-no-files-found: error
  musl:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Build htcrypt
        uses: docker://golang:alpine
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        with:
          args: go build -o ./build/ ./cmd/adpcrypt
      - name: Build acmednsproxy
        uses: docker://golang:alpine
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        with:
          args: go build -o ./build/ ./cmd/acmednsproxy
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-${{ matrix.goos }}-${{ matrix.goarch }}-musl
          path: ./build/*
          if-no-files-found: error
  
  flaf:
    needs: [archive, server, tools]
    name: Flaf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-archive
          path: artifact/archive
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-server
          path: artifact/server
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-tools
          path: artifact/tools
      - name: Display structure of downloaded files
        run: ls -R