on:
  push:
    branches:
    - main

name: Make Relase
jobs:
  archive:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_archive.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-archive
          path: |
            ./dist/acmednsproxy-archive/*.zip
            ./dist/acmednsproxy-archive/*.tar.gz
          if-no-files-found: error
  server:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_server.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-server
          path: |
            ./dist/acmednsproxy-server/*.deb
            ./dist/acmednsproxy-server/*.apk
          if-no-files-found: error
  tools:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_tools.yaml --rm-dist --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-tools
          path: |
            ./dist/acmednsproxy-tools/*.deb
            ./dist/acmednsproxy-tools/*.apk
          if-no-files-found: error
  alpine:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Alpine Build APK
        id: build_alpine
        uses: KalleDK/actions-abuild@v0.0.21
        with:
          abuild_packager: Kalle M. Aagaard <alpine@k-moeller.dk>
          abuild_prefix: ./alpine
          abuild_repo_name: acmednsproxy
          abuild_pkg_ver: 0.0.0_git123
          abuild_pkg_commit: ${{ github.sha }}
          abuild_pkg_rel: 1
          abuild_key_name:  ${{ secrets.ABUILD_KEY_NAME }}
          abuild_key: ${{ secrets.ABUILD_KEY }}
          abuild_key_pub: ${{ secrets.ABUILD_KEY_PUB }}
          abuild_repo_url: https://kalledk.github.io/alpinerepo
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-alpine-repo
          path: ${{ steps.build_alpine.outputs.repo_path }}
          if-no-files-found: error
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.build_alpine.outputs.repo_path }} # The folder the action should deploy.

  
  flaf:
    needs: [archive, server, tools, alpine]
    name: Flaf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-archive
          path: artifact/archive
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-server
          path: artifact/server
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-tools
          path: artifact/tools
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-alpine
          path: artifact/alpine
      - name: Display structure of downloaded files
        run: ls -R