on:
  push:
    branches:
    - main

name: Make Relase
jobs:
  alpine:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - run: go version
      - run: go build -o ./build/htcrypt ./cmd/htcrypt
      - run: go build -o ./build/acmednsproxy ./cmd/acmednsproxy 
      - uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/*
          if-no-files-found: error
  flaf:
    needs: alpine
    name: Flaf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: acmednsproxy-linux-amd64
          path: artifact/linux-amd64
      - name: Display structure of downloaded files
        run: ls -R