on:
  push:
    branches:
    - main

name: Make Relase
jobs:
  alpine:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version-file: 'go.mod'
      - run: go version
      - run: mkdir ./build
      - run: go build ./cmd/htcrypt -o ./build/htcrypt
      - run: go build ./cmd/acmednsproxy -o ./build/acmednsproxy
      - uses: actions/upload-artifact@v3
        with:
          name: acmednsproxy-linux-amd64
          path: ./build/*
          if-no-files-found: error